# https://hub.docker.com/r/chatwoot/chatwoot/tags
FROM chatwoot/chatwoot:latest-ce

# Inyectamos correos traducidos
COPY templates/confirmation_instructions.html.erb \
     /app/views/devise/mailer/confirmation_instructions.html.erb
COPY templates/unlock_instructions.html.erb \
     /app/views/devise/mailer/unlock_instructions.html.erb
COPY templates/password_change.html.erb \
     /app/views/devise/mailer/password_change.html.erb
COPY templates/reset_password_instructions.html.erb \
     /app/views/devise/mailer/reset_password_instructions.html.erb
COPY templates/base.liquid \
     /app/views/layouts/mailer/base.liquid
COPY templates/devise.en.yml \
     /config/locales/devise.en.yml
COPY templates/login.json \
     /app/javascript/dashboard/i18n/locale/es/login.json
COPY templates/resetPassword.json \
     /app/javascript/dashboard/i18n/locale/es/resetPassword.json

RUN apk add --no-cache multirun postgresql-client

COPY --chmod=755 start.sh ./

ENTRYPOINT ["/bin/sh"]

CMD ["start.sh"]
