# https://hub.docker.com/r/chatwoot/chatwoot/tags
FROM chatwoot/chatwoot:latest

# Inyectamos correos traducidos
COPY templates/confirmation_instructions.html.erb \
     /app/app/views/devise/mailer/confirmation_instructions.html.erb
COPY templates/confirmation_instructions.text.erb \
     /app/app/views/devise/mailer/confirmation_instructions.text.erb
COPY templates/reset_password_instructions.html.erb \
     /app/app/views/devise/mailer/reset_password_instructions.html.erb
COPY templates/reset_password_instructions.text.erb \
     /app/app/views/devise/mailer/reset_password_instructions.text.erb

RUN apk add --no-cache multirun postgresql-client

COPY --chmod=755 start.sh ./

ENTRYPOINT ["/bin/sh"]

CMD ["start.sh"]
